### Tensor 이해 - 생성
- Tensor란? pytorch에서 데이터를 저장하는 객체
    * pytorch에서 데이터를 저장하는 객체
    * 모델에 입력/출력 데이터 형태

- 개발 버전 : v.2.4.1

In [3]:
# 모듈 로딩
import torch

print(f"torch v.{torch.__version__}")

torch v.2.4.1


In [6]:
def printInfo(obj, obj_name):
    print(f"\n[{obj_name}]")
    print(f"shape : {obj.shape}")
    print(f"ndim : {obj.ndim}차원")
    print(f"dtype : {obj.dtype}")
    print(f"device : {obj.device}")
    print(f"data : \n{obj.data}")

- 텐서 생성 [1] torch.tensor()

In [10]:
# 데이터 1개 즉, 스칼라
dataTF = torch.tensor(10)
printInfo(dataTF, 'dataTF')

dataTF = torch.tensor(10, dtype = torch.uint8)
printInfo(dataTF, 'dataTF')


[dataTF]
shape : torch.Size([])
ndim : 0차원
dtype : torch.int64
device : cpu
data : 
10

[dataTF]
shape : torch.Size([])
ndim : 0차원
dtype : torch.uint8
device : cpu
data : 
10


In [13]:
# 데이터 1개 즉, 행렬 2D
dataTF = torch.tensor([10])
printInfo(dataTF, 'dataTF')

dataTF = torch.tensor([10], dtype = torch.uint8)
printInfo(dataTF, 'dataTF')


[dataTF]
shape : torch.Size([1])
ndim : 1차원
dtype : torch.int64
device : cpu
data : 
tensor([10])

[dataTF]
shape : torch.Size([1])
ndim : 1차원
dtype : torch.uint8
device : cpu
data : 
tensor([10], dtype=torch.uint8)


In [14]:
# 데이터 1개 즉, 행렬 2D
dataTF = torch.tensor([[10]])
printInfo(dataTF, 'dataTF')

dataTF = torch.tensor([[10],[20]], dtype = torch.uint8)
printInfo(dataTF, 'dataTF')


[dataTF]
shape : torch.Size([1, 1])
ndim : 2차원
dtype : torch.int64
device : cpu
data : 
tensor([[10]])

[dataTF]
shape : torch.Size([2, 1])
ndim : 2차원
dtype : torch.uint8
device : cpu
data : 
tensor([[10],
        [20]], dtype=torch.uint8)


In [16]:
# 데이터 1개 즉, 4D
dataTF = torch.tensor([[[[10]]]])
printInfo(dataTF, 'dataTF')

dataTF = torch.tensor([[[[10],[20]]]], dtype = torch.uint8)
printInfo(dataTF, 'dataTF')


[dataTF]
shape : torch.Size([1, 1, 1, 1])
ndim : 4차원
dtype : torch.int64
device : cpu
data : 
tensor([[[[10]]]])

[dataTF]
shape : torch.Size([1, 1, 2, 1])
ndim : 4차원
dtype : torch.uint8
device : cpu
data : 
tensor([[[[10],
          [20]]]], dtype=torch.uint8)
