### Tensor 이해

In [18]:
# 모듈 로딩
import torch

- 타입 지정 Tensor 클래스 활용
    * 데이터 타입을 설정 후 생성
    * 데이터 사이즈 설정한 텐서 생성 시 사용
    * 데이터의 자료형 변환한 텐서 생성 시 사용

In [19]:
# 정수형 텐서 생성
data = [1.4, 2.8, 3.1]

In [20]:
# 1바이트 정수형 텐서 생성
dataTS1=torch.ShortTensor(data)
dataTS11 = torch.tensor(data, dtype = torch.int8)

print(dataTS1, dataTS11, sep = '\n')

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int8)


/var/folders/hf/j1jp3r4x3mgcms3hl1xy7krh0000gn/T/ipykernel_24283/2098263997.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS1=torch.ShortTensor(data)
/var/folders/hf/j1jp3r4x3mgcms3hl1xy7krh0000gn/T/ipykernel_24283/2098263997.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS11 = torch.tensor(data, dtype = torch.int8)


In [23]:
# 논리형 텐서 생성
dataTS1=torch.BoolTensor(data)
dataTS11 = torch.tensor(data, dtype = torch.bool)

print(dataTS1, dataTS11, sep = '\n')

tensor([True, True, True])
tensor([True, True, True])


In [29]:
# 실수형 텐서 생성
dataTS1=torch.DoubleTensor(data)
dataTS11 = torch.tensor(data, dtype = torch.float64)

print(dataTS1, dataTS11, sep = '\n')

tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)
tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)


- Tensor 저장 및 실행 위치 설정 ==> 속성 device 설정

In [34]:
# 실행 위치 => CPU / GPU
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
DEVICE

'cpu'

In [35]:
# 실수형 텐서 생성
dataTS1=torch.DoubleTensor(data)
dataTS11 = torch.tensor(data, dtype = torch.float64, device = DEVICE)

print(dataTS1, dataTS11, sep = '\n')

tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)
tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)
