### Tensor 이해

In [3]:
# 모듈 로딩
import torch

- 텐서 생성 [2] torch.rand()

In [27]:
# 0 <= ~ < 1 범위의 임의의 숫자 1개 추출 => rand()
torch.manual_seed(1)

dataTS1 = torch.rand(3)         # 1D Vector
dataTS2 = torch.rand(2, 3)      # 2D Matrix
dataTS3 = torch.rand(2, 1, 3)   # 3D Tensor

print(dataTS1, dataTS2, dataTS3, sep='\n')

tensor([0.7576, 0.2793, 0.4031])
tensor([[0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695]])
tensor([[[0.4388, 0.6387, 0.5247]],

        [[0.6826, 0.3051, 0.4635]]])


- 텐서 생성 [3] torch.randn()

In [26]:
datanTS1 = torch.randn(3)         # 1D Vector
datanTS2 = torch.randn(2, 3)      # 2D Matrix
datanTS3 = torch.randn(2, 1, 3)   # 3D Tensor

print(datanTS1, datanTS2, datanTS3, sep='\n')

tensor([ 2.0731, -1.9578,  2.8238])
tensor([[ 0.2384, -0.6317,  1.3790],
        [ 0.6429, -0.4019,  2.5451]])
tensor([[[ 0.0080,  1.2720,  0.9502]],

        [[ 0.1889, -0.7525, -0.1523]]])


- 텐서 생성 [4] torch.randint()

In [28]:
torch.randint(1, 5, (3, 5)) # 1 ~ 4 범위의 정수를 3행 5열로 생성

tensor([[1, 3, 2, 3, 1],
        [3, 2, 3, 1, 4],
        [1, 3, 1, 2, 3]])

In [58]:
torch.randint(1, 46, (4, 6)) # 1 ~ 4 범위의 정수를 3행 5열로 생성

tensor([[ 1, 40, 15, 38,  5, 26],
        [29, 21, 41, 23, 13, 21],
        [45, 14, 24,  3, 37, 38],
        [ 3, 30, 15, 14, 15, 25]])