#### 1. Numpy 기본 사용법

In [19]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
array1 = np.arange(0, 10)
array2 = np.arange(10, 20)
np.savez('saved.npz', array1 = array1, array2 = array2)

In [3]:
data = np.load('saved.npz')
result1 = data['array1']
result2 = data['array2']
print(result1)
print(result2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


Numpy 원소 오름차순 정렬

In [5]:
array= np.array([5, 9, 10, 3, 1])
array.sort()
print(array)

[ 1  3  5  9 10]


Numpy 원소 내림차순 정렬

In [6]:
print(array[::-1])

[10  9  5  3  1]


각 열을 기준으로 정렬

In [12]:
a = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
print(a)

a.sort(axis = 0)
print(a)

[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


균일한 간격으로 데이터 생성

In [13]:
array = np.linspace(0, 10, 5)
print(array)

[ 0.   2.5  5.   7.5 10. ]


난수의 재현 (실행마다 결과 동일)

In [14]:
np.random.seed(7)
print(np.random.randint(0, 10, (2, 3)))

[[4 9 6]
 [3 3 7]]


Numpy 배열 객체 복사

In [16]:
array1 = np.arange(0, 10)
array2 = array1.copy()
array2[0] = 99

print(array1)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[99  1  2  3  4  5  6  7  8  9]


중복된 원소 제거

In [18]:
array = np.array([1, 1, 2, 2, 3, 3, 4])
print(np.unique(array))

[1 2 3 4]
