## 리스트 구조

In [708]:
l = [[1, 2, 3], [4, 5, 6]]

In [709]:
type(l)

list

## 리스트 인덱스 검색

In [710]:
l[0]

[1, 2, 3]

In [711]:
l[1]

[4, 5, 6]

## 리스트 내의 리스트 검색

In [712]:
for i,a in enumerate(l):
    for j, b in enumerate(a):
        print(l[i][j])

1
2
3
4
5
6


## 다차원 배열 구조

In [713]:
import numpy as np

In [714]:
np.__version__

'1.26.4'

## 다차원 배열 클래스

In [715]:
print(np.ndarray)

<class 'numpy.ndarray'>


In [716]:
np.ndarray.__name__

'ndarray'

In [717]:
for i in dir(np.ndarray):
    if not i.startswith("_"):
        if type(np.ndarray.__dict__[i]) != type(np.ndarray.var):
            print(i)

T
base
ctypes
data
dtype
flags
flat
imag
itemsize
nbytes
ndim
real
shape
size
strides


## 다차원 배열 만들기

In [718]:
l = [1, 2, 3, 4]

In [719]:
a = np.array(l)

In [720]:
a

array([1, 2, 3, 4])

In [721]:
type(a)

numpy.ndarray

In [722]:
t = (1, 2, 3, 4)

In [723]:
b = np.array(t)

In [724]:
type(b)

numpy.ndarray

## 다차원 배열 데이터 관리

In [725]:
a.data

In [726]:
a.data.obj

array([1, 2, 3, 4])

In [727]:
type(a.data.obj)

numpy.ndarray

## 다차원 배열 자료형관리

In [728]:
e = np.array(l, dtype = np.float_)

In [729]:
e

array([1., 2., 3., 4.])

In [730]:
e.dtype

dtype('float64')

## 2차원 배열의 정보 확인

In [731]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])

In [732]:
a2.shape

(2, 3)

In [733]:
a2.ndim

2

In [734]:
a2.dtype

dtype('int64')

In [735]:
a2.itemsize

8

In [736]:
a2.size

6

In [737]:
a2.strides

(24, 8)

## 대표적인 다차원 배열

In [738]:
np.ndarray.__base__

object

In [739]:
np.matrix.__bases__

(numpy.ndarray,)

## 유니버셜 함수

In [740]:
a = dir(np)
np.ufunc

numpy.ufunc

## 벡터화 연산

In [741]:
a = np.arange(6, 10)

In [742]:
a

array([6, 7, 8, 9])

In [743]:
b = np.arange(10, 14)

In [744]:
b

array([10, 11, 12, 13])

In [745]:
c = a * b

In [746]:
c

array([ 60,  77,  96, 117])

## 축 연산

In [747]:
a2 = np.array([1, 2, 3, 4])

In [748]:
a2

array([1, 2, 3, 4])

In [749]:
a2 = a2.reshape(2, 2)

In [750]:
a2

array([[1, 2],
       [3, 4]])

In [751]:
np.sum(a2)

10

In [752]:
np.sum(a2, axis = 0)

array([4, 6])

In [753]:
np.sum(a2, axis = 1)

array([3, 7])

## 배열의 원소 개수 일치

In [754]:
a = np.array([4, 5])

In [755]:
a.shape

(2,)

In [756]:
b = np.array([3, 4, 5])

In [757]:
b.shape

(3,)

In [758]:
try:
    a + b
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,) (3,) 


## 배열을 다른 변수에 할당

In [759]:
a = np.array([[1, 2], [3, 4]])

In [760]:
a

array([[1, 2],
       [3, 4]])

In [761]:
b = a

In [762]:
b

array([[1, 2],
       [3, 4]])

In [763]:
b[0] = 999

In [764]:
a

array([[999, 999],
       [  3,   4]])

In [765]:
b

array([[999, 999],
       [  3,   4]])

## 배열의 복사/뷰 확인

In [766]:
f = np.array([4, 5, 6, 7, 8])

In [767]:
e = f.copy()

In [768]:
q = f[:]

In [769]:
q.base

array([4, 5, 6, 7, 8])

In [770]:
np.may_share_memory(q, f)

True

## 리스트 검색

In [771]:
l = list(range(1, 10))

In [772]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [773]:
index = l

In [774]:
index = slice(1, 3)

In [775]:
l.__getitem__(index)

[2, 3]

## 다차원 배열 검색 1

In [776]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

In [777]:
index = l

In [778]:
index = slice(1, 3)

In [779]:
l.__getitem__(index)

[2, 3]

## 다차원 배열 검색 2

In [780]:
index = l

In [781]:
index = [1]

In [782]:
a.__getitem__(index)

array([2])

In [783]:
index = a < 4

In [784]:
index

array([ True,  True,  True, False, False, False, False])

In [785]:
a.__getitem__(index)

array([1, 2, 3])

In [786]:
a

array([1, 2, 3, 4, 5, 6, 7])

## Scalar - 0차원

In [787]:
a = np.array(43)

In [788]:
type(a)

numpy.ndarray

In [789]:
a

array(43)

In [790]:
a.ndim

0

In [791]:
a.shape

()

In [792]:
a.dtype

dtype('int64')

In [793]:
a == 43

True

## Vector - 1차원

In [794]:
v = np.array([43])

In [795]:
type(v)

numpy.ndarray

In [796]:
v

array([43])

In [797]:
v.ndim

1

In [798]:
v.shape

(1,)

## 벡터 생성 함수 1

In [799]:
v = np.arange(10)

In [800]:
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [801]:
v.dtype

dtype('int64')

In [802]:
v1 = np.arange(10.5, 20.5, 0.5)

In [803]:
v1

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [804]:
v1.dtype

dtype('float64')

In [805]:
v1.size

20

## 벡터 생성 함수 2

In [806]:
la = np.linspace(1, 10, 10)

In [807]:
la

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [808]:
la.dtype

dtype('float64')

In [809]:
lal = np.linspace(1, 10, 10, endpoint=False, retstep=True)

In [810]:
lal

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

## 벡터 생성 함수 3

In [811]:
lo = np.logspace(0, 2, 4) # log(x)값이 0~2 범위일때 x를 4등분

In [812]:
lo

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

In [813]:
la2 = np.linspace(0, 2, 4)

In [814]:
la2

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [815]:
for i in la2:
    print(np.power(10, i))

1.0
4.641588833612778
21.544346900318832
100.0


## 벡터 크기

In [816]:
v = np.arange(3, 5)

In [817]:
v

array([3, 4])

In [818]:
np.hypot(v[0], v[1]) # 빗변의 길이를 구하는 함수 (벡터)

5.0

In [819]:
v_p = np.power(v, 2)

In [820]:
v_r = np.sqrt(np.sum(v_p))

In [821]:
v_r

5.0

In [822]:
np.linalg.norm(v) # 벡터를 구해주는 함수

5.0

## 표준 단위 벡터

In [823]:
e1 = np.array([1, 0, 0])

In [824]:
np.linalg.norm(e1)

1.0

In [825]:
e2 = np.array([0, 1, 0])

In [826]:
np.linalg.norm(e2)

1.0

In [827]:
e3 = np.array([0, 0, 1])

In [828]:
np.linalg.norm(e3)

1.0

## 단위 벡터

In [829]:
v_3 = np.array([1, 2, 3])

In [830]:
v_3_n = np.linalg.norm(v_3)

In [831]:
v_3_n

3.7416573867739413

In [832]:
v_3_u = v_3 / v_3_n

In [833]:
v_3_u

array([0.26726124, 0.53452248, 0.80178373])

In [834]:
np.linalg.norm(v_3_u)

1.0

## 벡터의 상등

In [835]:
a = np.arange(3, 5)

In [836]:
b = np.arange(3, 5)

In [837]:
np.array_equal(a, b)

True

In [838]:
a_l = np.linalg.norm(a)

In [839]:
b_l = np.linalg.norm(b)

In [840]:
a_l == b_l

True

## 벡터의 거리

In [841]:
c = np.arange(10, 13)

In [842]:
d = np.arange(0, 3)

In [843]:
np.sqrt(np.sum(np.square(c-d)))

17.320508075688775

In [844]:
np.linalg.norm(c-d)

17.320508075688775

## 행렬 만들기

In [845]:
A = np.array([[43], [44]])

In [846]:
type(A)

numpy.ndarray

In [847]:
A

array([[43],
       [44]])

In [848]:
A.dtype

dtype('int64')

In [849]:
A.ndim

2

In [850]:
A.shape

(2, 1)

## 행렬 랭크

In [851]:
cl = np.array([[1, 2, 4], [2, 4, 8], [3, 4, 5]])

In [852]:
np.linalg.matrix_rank(cl)

2

In [853]:
np.linalg.det(cl)

0.0

In [854]:
cl[0] * 2 - cl[1]

array([0, 0, 0])

In [855]:
c2 = np.array([[1, 3, 4], [1, 8, 5], [2, 3, 4]])

In [856]:
np.linalg.matrix_rank(c2)

3

In [857]:
np.linalg.det(c2)

-17.0

In [858]:
np.linalg.matrix_rank(c2.T)

3

## 축 알아보기 1

In [859]:
A = np.array([[2, 3], [4, 5]])

In [860]:
A.sum()

14

In [861]:
A.sum(axis = 0)

array([6, 8])

In [862]:
A.sum(axis = 1)

array([5, 9])

## 축 알아보기 2

In [863]:
c = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])

In [864]:
c.ndim

3

In [865]:
c.shape

(2, 2, 2)

In [866]:
c[0]

array([[1, 2],
       [3, 4]])

In [867]:
c[1]

array([[5, 6],
       [7, 8]])

In [868]:
c.sum(axis = 0)

array([[ 6,  8],
       [10, 12]])

In [869]:
c.sum(axis = 1)

array([[ 4,  6],
       [12, 14]])

In [870]:
c.sum(axis = 2)

array([[ 3,  7],
       [11, 15]])

## 확장 및 축소하기

In [871]:
x = np.array([1, 2])

In [872]:
x

array([1, 2])

In [873]:
y = np.expand_dims(x, axis = 1)

In [874]:
y

array([[1],
       [2]])

In [875]:
z = np.expand_dims(x, axis = 0)

In [876]:
z

array([[1, 2]])

In [877]:
x = np.array([[1, 4, 5], [4, 5, 6], [7, 8, 9]])

In [878]:
x

array([[1, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [879]:
x.flatten()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [880]:
x.ravel()

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

## 정사각행렬

In [881]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 8]])

In [882]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [883]:
a.shape

(3, 3)

In [884]:
np.trace(a) # 대각 원소의 합

14

In [885]:
a.trace()

14

## 대각행렬

In [886]:
b = np.array([[1, 0, 0], [0, 3, 0], [0, 0, 5]])

In [887]:
b

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [888]:
b.diagonal()

array([1, 3, 5])

In [889]:
np.diagonal(b)

array([1, 3, 5])

## 삼각행렬

In [890]:
a = np.arange(1, 10).reshape(3, 3)

In [891]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [892]:
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [893]:
b = np.arange(1, 10).reshape(3, 3)

In [894]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [895]:
np.triu(b)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

## 대칭행렬

In [896]:
x = np.array([[1, 2, 3], [2, 3, 5], [3, 5, 6]])

In [897]:
x

array([[1, 2, 3],
       [2, 3, 5],
       [3, 5, 6]])

In [898]:
x.T

array([[1, 2, 3],
       [2, 3, 5],
       [3, 5, 6]])

In [899]:
np.array_equal(x, x.T)

True

In [900]:
np.array_equiv(x, x.T)

True

## 치환행렬

In [901]:
a = np.arange(1, 10).reshape(3, 3)

In [902]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [903]:
b = np.eye(3, dtype = 'int') # 3x3 단위행렬을 정수형으로 생성

In [904]:
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [905]:
np.dot(a, b) # 행렬곱

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [906]:
c = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])

In [907]:
np.dot(a, c)

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

## 직교행렬

In [908]:
from scipy.stats import ortho_group

In [909]:
x = ortho_group.rvs(3) # 정규 직교행렬 생성 함수 (3x3 직교 행렬)

In [910]:
x

array([[-0.42186977, -0.9035368 , -0.0751475 ],
       [-0.83912071,  0.42049168, -0.34505534],
       [ 0.34336909, -0.0825106 , -0.93556917]])

In [911]:
i3 = np.dot(x, x.T)

In [912]:
i3

array([[ 1.00000000e+00,  8.68345275e-17,  2.48371437e-17],
       [ 8.68345275e-17,  1.00000000e+00, -1.51806970e-17],
       [ 2.48371437e-17, -1.51806970e-17,  1.00000000e+00]])

In [913]:
c = np.eye(3) # 3x3 단위행렬 생성

In [914]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [915]:
np.allclose(c, i3) # 단위행렬 c랑 직교행렬의 행렬곱으로 계산한 행렬이 거의 같은지
# 부동 소숫점 연산의 오차는 무시함

True

## 전치행렬

In [916]:
a = np.array([[1, 2], [3, 4]])

In [917]:
a

array([[1, 2],
       [3, 4]])

In [918]:
a.T

array([[1, 3],
       [2, 4]])

In [919]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [920]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

## 색인검색

In [921]:
v = np.array([1, 2, 3, 4, 5])

In [922]:
v[0]

1

In [923]:
v[-1]

5

In [924]:
A = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [925]:
A[0]

array([1, 2, 3, 4, 5])

In [926]:
A[-1]

array([ 6,  7,  8,  9, 10])

## 슬라이스 검색

In [927]:
B = np.arange(9).reshape(3, 3)

In [928]:
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [929]:
B.shape

(3, 3)

In [930]:
B[0, :]

array([0, 1, 2])

In [931]:
B[0]

array([0, 1, 2])

In [932]:
B[:,0]

array([0, 3, 6])

## 생략기호를 사용한 접근

In [933]:
A = np.arange(1, 60, 5).reshape(3, 4)

In [934]:
A

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [935]:
A[...]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [936]:
A[:2, ...]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36]])

In [937]:
A[..., :2]

array([[ 1,  6],
       [21, 26],
       [41, 46]])

## 논리 검색 1

In [938]:
L = np.random.randn(7, 4)

In [939]:
L

array([[ 0.50001261,  0.71447615, -0.31115242, -0.20882081],
       [ 0.02177925, -0.2130405 , -0.81414701, -0.41718349],
       [ 1.19803232, -0.58022611,  1.79375082,  0.81820723],
       [ 0.52940438,  1.9180957 , -1.03078109, -0.07951945],
       [ 0.26414525,  1.06008891, -0.99851317, -0.60898751],
       [ 0.32001194,  0.08202536, -1.09391524,  0.89930037],
       [ 0.27325755, -0.61028191, -0.9634476 ,  0.25451839]])

In [940]:
L[L < 0]

array([-0.31115242, -0.20882081, -0.2130405 , -0.81414701, -0.41718349,
       -0.58022611, -1.03078109, -0.07951945, -0.99851317, -0.60898751,
       -1.09391524, -0.61028191, -0.9634476 ])

## 논리 검색 2

In [941]:
L[L < 0] = 999

In [942]:
L

array([[5.00012611e-01, 7.14476146e-01, 9.99000000e+02, 9.99000000e+02],
       [2.17792455e-02, 9.99000000e+02, 9.99000000e+02, 9.99000000e+02],
       [1.19803232e+00, 9.99000000e+02, 1.79375082e+00, 8.18207226e-01],
       [5.29404376e-01, 1.91809570e+00, 9.99000000e+02, 9.99000000e+02],
       [2.64145246e-01, 1.06008891e+00, 9.99000000e+02, 9.99000000e+02],
       [3.20011943e-01, 8.20253604e-02, 9.99000000e+02, 8.99300375e-01],
       [2.73257546e-01, 9.99000000e+02, 9.99000000e+02, 2.54518393e-01]])

In [943]:
LC = L[L == 999]

In [944]:
LC

array([999., 999., 999., 999., 999., 999., 999., 999., 999., 999., 999.,
       999., 999.])

## 논리 검색 3

In [945]:
L = np.arange(0, 12)

In [946]:
L

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [947]:
try:
    L and L
except Exception as e:
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [948]:
np.logical_and(L, L)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [949]:
L[np.logical_and(L, L)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 펜시 검색 1

In [950]:
x = np.arange(1, 15)

In [951]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [952]:
pos2 = np.array([1, 2, 2, 2])

In [953]:
x[pos2]

array([2, 3, 3, 3])

In [954]:
c = x[pos2]

In [955]:
np.may_share_memory(x, c)

False

In [956]:
y = x[:4]

In [957]:
np.may_share_memory(x, y)

True

## 팬시 검색 2

In [958]:
x = np.arange(16).reshape(4, 4)

In [959]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [960]:
x[[3, 0]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [961]:
x[[1, 2], [2, 3]] # 1번행에서 2번째값, 2번행에서 3번째값

array([ 6, 11])

In [962]:
a = np.array([[2, 3, 4, 5], [8, 9, 0, 1]])

In [963]:
a

array([[2, 3, 4, 5],
       [8, 9, 0, 1]])

In [964]:
type(np.ix_)

numpy._ArrayFunctionDispatcher

In [965]:
a[np.ix_([0,1], [0,2])] # 행에서 0,1인덱스 가져오고 열에서 0,2인덱스 가져오기

array([[2, 4],
       [8, 0]])

## 팬시 검색 혼용

In [966]:
x = np.arange(10).reshape(2, 5)

In [967]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [968]:
x[0, [0,1]] # 0행에서 0,1열을 가져옴

array([0, 1])

In [969]:
x[1, [0,1]] # 1행에서 0,1열을 가져옴

array([5, 6])

In [970]:
x[[0, 1]] # 0,1행을 가져옴

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [971]:
x[[0, 1], 0] # 0,1행에서 0열을 가져옴

array([0, 5])

In [972]:
a = x[[0, 1], 0]

In [973]:
a

array([0, 5])

In [974]:
np.may_share_memory(x, a)

False

## 팬시검색을 이용한 축소 및 확대

In [975]:
x = np.arange(9).reshape(3, 3)

In [976]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [977]:
a = x[1:, 1:]

In [978]:
a

array([[4, 5],
       [7, 8]])

In [979]:
np.may_share_memory(x, a)

True

In [980]:
a = np.reshape(np.arange(10), (2, 5))

In [981]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [982]:
c = a[[1, 1, 1], np.newaxis]

In [983]:
c

array([[[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]]])

In [984]:
np.reshape(np.arange(10), (2, 5))[[1, 1, 1], np.newaxis]

array([[[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]]])

In [985]:
c.shape

(3, 1, 5)

## 메소드로 검색 1

In [986]:
x = np.arange(9).reshape(3, 3)

In [987]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [988]:
x.item(1)

1

In [989]:
x.item(5)

5

In [990]:
x.item(1, 2)

5

In [991]:
x.item((2, 2)) # 2행 2열

8

In [992]:
x.itemset(2, 20) # 2번째 원소는 20으로

In [993]:
x

array([[ 0,  1, 20],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [994]:
x.itemset((1, 2), 20)

In [995]:
x

array([[ 0,  1, 20],
       [ 3,  4, 20],
       [ 6,  7,  8]])

In [996]:
x.view()

array([[ 0,  1, 20],
       [ 3,  4, 20],
       [ 6,  7,  8]])

## 메소드로 검색 2

In [997]:
b = np.linspace(1, 10, 10).reshape(2, 5)

In [998]:
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [999]:
pos1 = [3, 4]

In [1000]:
b.take(pos1) # b에서 3,4번째 원소

array([4., 5.])

In [1001]:
pos2 = [[0, 1], [3, 4]]

In [1002]:
b.take(pos2)

array([[1., 2.],
       [4., 5.]])

In [1003]:
c = b.copy()

In [1004]:
np.may_share_memory(c, b)

False

In [1005]:
c.put(pos1, 30) # c에서 3,4번째 원소 30,30으로 바꿈

In [1006]:
c

array([[ 1.,  2.,  3., 30., 30.],
       [ 6.,  7.,  8.,  9., 10.]])

In [1007]:
c.put(pos1, (50, 50)) # c에서 3,4번째 원소 50,50으로 바꿈

In [1008]:
c

array([[ 1.,  2.,  3., 50., 50.],
       [ 6.,  7.,  8.,  9., 10.]])

## 질의 함수 1

In [1009]:
x = np.arange(9).reshape(3, 3)

In [1010]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [1011]:
np.choose(0, x) # x의 0번째 행을 선택

array([0, 1, 2])

In [1012]:
np.choose([0], x)

array([0, 1, 2])

In [1013]:
np.choose(tuple([0,1,2]),x)
# 튜플로 choose 하면 (0,1,2)각각은 0번째, 1번째, 2번째 배열에서 추출

array([0, 4, 8])

## 질의 함수 2

In [1014]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [1015]:
np.where(x > 4) # 4보다 큰 원소들은
# 1행 2열 (5)
# 2행 0열 (6)
# 2행 1열 (7)
# 2행 2열 (8)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

## 벡터 덧셈

In [1016]:
d = np.array([3, 4])

In [1017]:
e = np.array([5, 6])

In [1018]:
d + e

array([ 8, 10])

In [1019]:
np.add(d, e)

array([ 8, 10])

In [1020]:
f = np.array([1, 2, 3])

In [1021]:
try:
    f + e
except Exception as ex:
    print(ex)

operands could not be broadcast together with shapes (3,) (2,) 


## 벡터 뺄셈

In [1022]:
d = np.array([3, 4])

In [1023]:
e = np.array([5, 6])

In [1024]:
d - e

array([-2, -2])

In [1025]:
np.subtract(d, e)

array([-2, -2])

In [1026]:
d + (-e)

array([-2, -2])

In [1027]:
np.add(d, np.negative(e))

array([-2, -2])

## 스칼라 곱셈

In [1028]:
d = np.array([2, 3])

In [1029]:
3 * d # 3 * [2, 3]

array([6, 9])

In [1030]:
np.array([3, 3]) * d # [3, 3] * [2, 3]

array([6, 9])

In [1031]:
np.multiply(3, d) # 3 * [2, 3]

array([6, 9])

In [1032]:
np.multiply(np.array([3, 3]), d) # [3, 3] * [2, 3]

array([6, 9])

## 브로드캐스팅

In [1033]:
x = np.arange(10).reshape(2, 5)

In [1034]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [1035]:
y = np.arange(5)

In [1036]:
y

array([0, 1, 2, 3, 4])

In [1037]:
z = np.broadcast(x, y)

In [1038]:
z

In [1039]:
type(z)

numpy.broadcast

In [1040]:
z.shape, z.ndim

((2, 5), 2)

In [1041]:
for i in z:
    print(i)

(0, 0)
(1, 1)
(2, 2)
(3, 3)
(4, 4)
(5, 0)
(6, 1)
(7, 2)
(8, 3)
(9, 4)


In [1042]:
x + y

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

## 브로드캐스팅 처리 규칙

In [1043]:
x2 = np.ones((2, 3))

In [1044]:
x2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [1045]:
x1 = np.ones(3)

In [1046]:
x1

array([1., 1., 1.])

In [1047]:
x1.shape, x2.shape

((3,), (2, 3))

In [1048]:
x1.shape[0] == x2.shape[1]

True

In [1049]:
x1 = x1[np.newaxis,]

In [1050]:
x1.shape

(1, 3)

In [1051]:
x1 = np.vstack((x1[0], x1[0])) # vertical stack : 행 추가

In [1052]:
x1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [1053]:
x11 = np.hstack((x1[0], 1)) # horizontal stack : 열 추가

In [1054]:
x11

array([1., 1., 1., 1.])

In [1055]:
x1.shape == x2.shape

True

In [1056]:
x1 + x2

array([[2., 2., 2.],
       [2., 2., 2.]])

## 행벡터와 열벡터 브로드캐스트 확장

In [1058]:
x = np.arange(1, 4)

In [1059]:
x

array([1, 2, 3])

In [1060]:
x1 = x.reshape(1, 3)

In [1066]:
x1

array([[1, 2, 3]])

In [1062]:
x2 = x[np.newaxis,]

In [1067]:
x2

array([[1, 2, 3]])

In [1068]:
y = np.arange(1, 4)

In [1069]:
y

array([1, 2, 3])

In [1074]:
y1 = y.reshape(3, 1)

In [1075]:
y1

array([[1],
       [2],
       [3]])

In [1076]:
y2 = y[:, np.newaxis]

In [1077]:
y2

array([[1],
       [2],
       [3]])

In [1078]:
np.broadcast_arrays(x1, y1) # 같은 크기로 확장
# x1은 행방향으로 확장
# x2는 열방향으로 확장

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])]

In [1080]:
x1 + y1

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

## 벡터의 내적

In [1081]:
a = np.array([3, 4])

In [1082]:
b = np.array([5, 6])

In [1083]:
a @ b

39

In [1084]:
np.dot(a, b)

39

In [1085]:
np.inner(a, b)

39

## 벡터의 외적

In [1086]:
a = np.array([1, 4])

In [1087]:
b = np.array([3, 6])

In [1088]:
np.cross(a, b)

array(-6)

In [1089]:
c = np.array([1, 4, 3])

In [1090]:
d = np.array([3, 4, 5])

In [1091]:
np.cross(c, d) # 외적 (직각 벡터)

array([ 8,  4, -8])

In [1101]:
a = [[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]]]
b = [[[1, 2, 3, 4, 5]], [[1, 2, 3, 4, 5]]]

In [1102]:
np.shape(a)

(1, 2, 5)

In [1097]:
np.shape(b)

(2, 1, 5)

## 행렬식

In [1103]:
a = np.array([[3, 1], [2, 2]])

In [1104]:
np.linalg.det(a)

4.000000000000001

In [1105]:
np.allclose(4.0, np.linalg.det(a))

True

## 행렬식

In [1106]:
b = np.array([[3, 1, 3], [2, 2, 3], [1, 1, 1]])

In [1107]:
b

array([[3, 1, 3],
       [2, 2, 3],
       [1, 1, 1]])

In [1108]:
3 * np.linalg.det(b[1:, 1:])

-3.0

In [1109]:
np.linalg.det(b[1:, :2])

0.0

In [1110]:
3 * np.linalg.det(b[1:, :2])

0.0

In [1111]:
-3 + 1 + 0

-2

In [1112]:
np.linalg.det(b)

-2.0

## 역행렬

In [1113]:
a = np.array([[3, 2], [6, 4]])

In [1114]:
np.linalg.det(a)

0.0

In [1115]:
b = np.array([[1, 2, 3], [4, 5, 6], [3, 2, 4]])

In [1116]:
np.linalg.det(b)

-9.000000000000002

In [1117]:
bi = np.linalg.inv(b)

In [1119]:
bb = np.dot(b, bi)

In [1120]:
np.allclose(np.eye(3), bb)

True

## 역행렬의 교환법칙

In [1121]:
a = np.array([[1, 2], [3, 4]])

In [1122]:
a

array([[1, 2],
       [3, 4]])

In [1123]:
ai = np.linalg.inv(a)

In [1124]:
ai

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [1125]:
x = np.dot(a, ai)

In [1126]:
x

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [1127]:
y = np.dot(ai, a)

In [1128]:
y

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [1129]:
np.allclose(np.eye(2), y)

True

In [1130]:
np.allclose(x, y)

True

## 역행렬의 분배처리

In [1131]:
a = np.array([[1, 2], [3, 4]])

In [1132]:
np.linalg.det(a)

-2.0000000000000004

In [1133]:
b = np.array([[3, 4], [1, 2]])

In [1134]:
np.linalg.det(b)

2.0000000000000004

In [1135]:
ai = np.linalg.inv(a)

In [1136]:
bi = np.linalg.inv(b)

In [1137]:
ab = np.linalg.inv(np.dot(a, b)) # 행렬곱을 역행렬

In [1138]:
ba = np.dot(bi, ai) # 각 역행렬을 행렬곱

In [1139]:
np.allclose(ab, ba) # 둘의 결과는 같다

True

## 배열의 형상 변경

In [1142]:
x = np.arange(16)

In [1143]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [1144]:
xl = x.reshape(2, 8)

In [1145]:
xl

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [1146]:
try:
    x2 = x.reshape(4, 5)
except Exception as e:
    print(e)
# 16개의 원소를 4 x 5로 변환 불가

cannot reshape array of size 16 into shape (4,5)


In [1147]:
y1 = x.reshape(4, -1) # -1은 자동으로 형상 세팅

In [1148]:
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## 배열의 크기 변경

In [1149]:
a = np.arange(4)

In [1150]:
a

array([0, 1, 2, 3])

In [1151]:
np.resize(a, 8)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [1152]:
np.append(a, a)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [1153]:
b = np.arange(4)

In [1154]:
b.resize((4, 4))

In [1155]:
b

array([[0, 1, 2, 3],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [1156]:
c = np.arange(8)

In [1157]:
c

array([0, 1, 2, 3, 4, 5, 6, 7])

In [1158]:
c.resize(4, refcheck=False)

In [1159]:
c

array([0, 1, 2, 3])

## 1차원 배열을 2차원 배열로 변경 1

In [1163]:
x = np.arange(3)

In [1164]:
y = np.arange(4)

In [1165]:
x_, y_ = np.meshgrid(x, y)
# x는 행방향으로 확장
# y는 열방향으로 확장

In [1166]:
x_

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [1167]:
y_

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [1168]:
x_1 = x.reshape(1, -1)

In [1169]:
np.concatenate([x_1, x_1, x_1, x_1])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [1173]:
y_1 = y.reshape(-1, 1)

In [1174]:
np.concatenate([y_1, y_1, y_1, y_1], axis = 1)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

## 1차원 배열을 2차원 배열로 변경 2

In [1177]:
np.arange(10, 30, 10)

array([10, 20])

In [1178]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [1179]:
np.broadcast_arrays(np.arange(10, 30, 10).reshape(2, 1),
                    np.arange(1, 5).reshape(1, 4))
# 2행 1열과 1행 4열을 연산하려면 2행 4열이 되어야 하므로
# 위에꺼는 열방향으로 확장, 아래꺼는 행방향으로 확장

[array([[10, 10, 10, 10],
        [20, 20, 20, 20]]),
 array([[1, 2, 3, 4],
        [1, 2, 3, 4]])]

In [1180]:
a, b = np.mgrid[10:30:10, 1:5]

In [1181]:
a

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [1182]:
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

## 1차원 배열을 2차원 배열로 변경 3

In [1184]:
c, d = np.ogrid[10:30:10, 1:5]

In [1185]:
c

array([[10],
       [20]])

In [1186]:
d

array([[1, 2, 3, 4]])

In [1187]:
e, f = np.broadcast_arrays(c, d)

In [1188]:
e

array([[10, 10, 10, 10],
       [20, 20, 20, 20]])

In [1189]:
f

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

## 축이 1인 차원을 줄이기

In [1190]:
x = np.array([[[0], [1], [2]]])

In [1191]:
x

array([[[0],
        [1],
        [2]]])

In [1193]:
x.shape

(1, 3, 1)

In [1194]:
np.squeeze(x)

array([0, 1, 2])

In [1195]:
np.squeeze(x, axis = 0)

array([[0],
       [1],
       [2]])

In [1196]:
np.squeeze(x, axis = 2)

array([[0, 1, 2]])

## 내부 원소를 가지고 배열 확대하기

In [1197]:
a = np.linspace(1, 5, 5, dtype = np.int32)

In [1198]:
a

array([1, 2, 3, 4, 5], dtype=int32)

In [1199]:
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5], dtype=int32)

In [1200]:
e = np.arange(4).reshape(2, 2)

In [1201]:
e

array([[0, 1],
       [2, 3]])

In [1204]:
np.tile(e, 2)

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

## 배열을 결합하기

In [1205]:
a = np.linspace(1, 6, 6, dtype = np.int32).reshape(2, 3)

In [1206]:
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [1209]:
b = np.linspace(7, 13, 6, dtype = np.int32).reshape(2, 3)

In [1210]:
b

array([[ 7,  8,  9],
       [10, 11, 13]], dtype=int32)

In [1211]:
np.concatenate([a, b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 13]], dtype=int32)

In [1212]:
np.concatenate([a, b], axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 13]], dtype=int32)

## 배열을 쌓기

In [1213]:
x = np.array([1, 2, 3])

In [1214]:
y = np.array([4, 5, 6])

In [1215]:
np.stack([x, y])

array([[1, 2, 3],
       [4, 5, 6]])

In [1216]:
np.stack([x, y], axis = 0)

array([[1, 2, 3],
       [4, 5, 6]])

In [1217]:
a = np.vstack([x, y])

In [1218]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [1219]:
np.vstack([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [1220]:
np.stack([x, y], axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [1221]:
b = np.hstack([x, y])

In [1222]:
b

array([1, 2, 3, 4, 5, 6])

## 배열을 분리하기

In [1223]:
a = np.linspace(1, 6, 6, dtype = np.int32).reshape(2, 3)

In [1224]:
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [1225]:
b = np.vstack([a, a])

In [1226]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [1227]:
x, y = np.split(b, [2])

In [1228]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [1229]:
y

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

## 배열 쌓기 객체

In [1230]:
x = np.arange(6).reshape(2, 3)

In [1231]:
c = np.random.randn(2, 3)

In [1232]:
np.r_[a, c]

array([[ 1.        ,  2.        ,  3.        ],
       [ 4.        ,  5.        ,  6.        ],
       [-0.23892277, -0.99085098,  0.56498552],
       [-0.49511002,  0.50802559,  0.9193654 ]])

In [1233]:
np.c_[a, c]

array([[ 1.        ,  2.        ,  3.        , -0.23892277, -0.99085098,
         0.56498552],
       [ 4.        ,  5.        ,  6.        , -0.49511002,  0.50802559,
         0.9193654 ]])